// <auto-generated />
using System;
using System.Collections.Generic;
using AccelokaSandy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccelokaSandy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301093323_TestedChangeOnDiscriminatorValue")]
    partial class TestedChangeOnDiscriminatorValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quota")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);

                    b.HasDiscriminator<string>("TicketType").HasValue("TicketBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TicketCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TicketCategoryName")
                        .IsUnique();

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("BookedTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BookedTicketCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "BookedTicketCode");

                    b.HasIndex("TicketId");

                    b.ToTable("BookedTickets");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.FlightTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaggageKg")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransitsCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("flight");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketBase", b =>
                {
                    b.HasOne("AccelokaSandy.Domain.Entities.TicketCategory", "TicketCategory")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("BookedTicket", b =>
                {
                    b.HasOne("AccelokaSandy.Domain.Entities.TicketBase", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketCategory", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
