// <auto-generated />
using System;
using System.Collections.Generic;
using AccelokaSandy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccelokaSandy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301163045_AddedTheRestOfDiscriminatorValues")]
    partial class AddedTheRestOfDiscriminatorValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quota")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);

                    b.HasDiscriminator<string>("TicketType").HasValue("TicketBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TicketCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TicketCategoryName")
                        .IsUnique();

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("BookedTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BookedTicketCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "BookedTicketCode");

                    b.HasIndex("TicketId");

                    b.ToTable("BookedTickets");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.BusTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("ArrivalStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransitsCount")
                        .HasColumnType("integer");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Amenities")
                                .HasColumnName("BusTicket_Amenities");

                            t.Property("DepartureTime")
                                .HasColumnName("BusTicket_DepartureTime");

                            t.Property("Duration")
                                .HasColumnName("BusTicket_Duration");

                            t.Property("SeatClass")
                                .HasColumnName("BusTicket_SeatClass");

                            t.Property("TransitsCount")
                                .HasColumnName("BusTicket_TransitsCount");
                        });

                    b.HasDiscriminator().HasValue("bus");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.ConcertTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConcertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<List<string>>("Packages")
                        .HasColumnType("text[]");

                    b.Property<string>("SeatSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("ConcertTicket_Duration");

                            t.Property("SeatSection")
                                .HasColumnName("ConcertTicket_SeatSection");
                        });

                    b.HasDiscriminator().HasValue("concert");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.FlightTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaggageKg")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransitsCount")
                        .HasColumnType("integer");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Amenities")
                                .HasColumnName("FlightTicket_Amenities");

                            t.Property("DepartureTime")
                                .HasColumnName("FlightTicket_DepartureTime");

                            t.Property("Duration")
                                .HasColumnName("FlightTicket_Duration");

                            t.Property("SeatClass")
                                .HasColumnName("FlightTicket_SeatClass");

                            t.Property("TransitsCount")
                                .HasColumnName("FlightTicket_TransitsCount");
                        });

                    b.HasDiscriminator().HasValue("flight");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.HotelTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MaxCheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MinCheckInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Amenities")
                                .HasColumnName("HotelTicket_Amenities");
                        });

                    b.HasDiscriminator().HasValue("hotel");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.MovieTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.Property<string>("Cinema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CinemaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("ScreeningTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeatSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("MovieTicket_Duration");
                        });

                    b.HasDiscriminator().HasValue("movie");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.SeaTransportationTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("ArrivalPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeparturePort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransitsCount")
                        .HasColumnType("integer");

                    b.Property<string>("TransportationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("seatransportation");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TrainTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.TicketBase");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransitsCount")
                        .HasColumnType("integer");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("Amenities")
                                .HasColumnName("TrainTicket_Amenities");

                            t.Property("DepartureTime")
                                .HasColumnName("TrainTicket_DepartureTime");

                            t.Property("Duration")
                                .HasColumnName("TrainTicket_Duration");

                            t.Property("SeatClass")
                                .HasColumnName("TrainTicket_SeatClass");

                            t.Property("TransitsCount")
                                .HasColumnName("TrainTicket_TransitsCount");
                        });

                    b.HasDiscriminator().HasValue("train");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketBase", b =>
                {
                    b.HasOne("AccelokaSandy.Domain.Entities.TicketCategory", "TicketCategory")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("BookedTicket", b =>
                {
                    b.HasOne("AccelokaSandy.Domain.Entities.TicketBase", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.TicketCategory", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
