// <auto-generated />
using System;
using System.Collections.Generic;
using AccelokaSandy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccelokaSandy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Bookings.BookedTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BookedTicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookingId1")
                        .HasColumnType("text");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotTotalPrice")
                        .HasColumnType("integer");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookedTicketCode")
                        .IsUnique();

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingId1");

                    b.HasIndex("TicketId");

                    b.ToTable("BookedTickets", (string)null);
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Categories.TicketCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TicketCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TicketCategoryName")
                        .IsUnique();

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.TicketBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Amenities")
                        .HasColumnType("jsonb")
                        .HasColumnName("Amenities");

                    b.Property<int?>("BaggageKg")
                        .HasColumnType("integer")
                        .HasColumnName("BaggageKg");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DepartureTime");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("Duration");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quota")
                        .HasColumnType("integer");

                    b.Property<string>("SeatClass")
                        .HasColumnType("text")
                        .HasColumnName("SeatClass");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int?>("TransitsCount")
                        .HasColumnType("integer")
                        .HasColumnName("TransitsCount");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);

                    b.HasDiscriminator<string>("TicketType").HasValue("TicketBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.BusTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("ArrivalStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("bus");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.ConcertTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConcertDate")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Packages")
                        .HasColumnType("text[]");

                    b.Property<string>("SeatSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Tickets", t =>
                        {
                            t.Property("SeatSection")
                                .HasColumnName("ConcertTicket_SeatSection");
                        });

                    b.HasDiscriminator().HasValue("concert");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.FlightTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("flight");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.HotelTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MaxCheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MinCheckInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("hotel");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.MovieTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("Cinema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CinemaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScreeningTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeatSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("movie");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.SeaTransportationTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("ArrivalPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeparturePort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("seatransportation");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.TrainTicket", b =>
                {
                    b.HasBaseType("AccelokaSandy.Domain.Entities.Tickets.TicketBase");

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("train");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Bookings.BookedTicket", b =>
                {
                    b.HasOne("Booking", "Booking")
                        .WithMany("BookedTickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking", null)
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId1");

                    b.HasOne("AccelokaSandy.Domain.Entities.Tickets.TicketBase", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Tickets.TicketBase", b =>
                {
                    b.HasOne("AccelokaSandy.Domain.Entities.Categories.TicketCategory", "TicketCategory")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("AccelokaSandy.Domain.Entities.Categories.TicketCategory", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.Navigation("BookedTickets");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
